# Playbook for Database Servers
# filename: mysql_create_db.yml 
---
   
- hosts: vmware
  become: true
  pre_tasks:
     - shell: echo 'I":" Beginning mysql_create_db '
  roles:
     - mysql_create_db
  post_tasks:
     - shell: echo 'I":" Done mysql_create_db ..'
